FROM gcc 

MAINTAINER @joshuacook

RUN apt-get update && \
      apt-get -y install \
      binutils \
      gdb \
      libcurl4-openssl-dev \
      libglib2.0-0 \
      libgsl0ldbl \
      libsqlite3-0 \
      libxml2 \
      valgrind 
